### ISSUE TITLE
How to predict values when only ID and SMILES are given

### ISSUE THREAD

**Issue by agrodet** [elix-tech/kmol#1]
Currently I have a file `data.csv` 
```
mol_id,smiles,25,43,47,50,51,52,56,61,72,86,87,88,93,96,100,102,106,107,121,125,126,127,129,134,136,137,144,155,165,169,170,219,227,249,252,259,10140,10472,10670,11359,104301,104302,104756,104828
CHEMBL10,[SH0](=O)(C)c1ccc(-c2[nH]c(c(-c3ccc(F)cc3)n2)-c2ccncc2)cc1,,,,,,,,,,,,,,1,,,,,,,,,,,,,,,,,,,,,1,,1,,,,,,,
CHEMBL1000,Clc1ccc(C(N2CCN(CCOCC(=O)O)CC2)c2ccccc2)cc1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,
CHEMBL100005,O=C(OC)C(Cc1cc2OCOc2cc1)c1c2c(nc3c1cccc3)cccc2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,
CHEMBL100007,Brc1cc(CC(NC)c2c(C)ccs2)c(N)cc1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,,
...
```

with a `config.json`
```json
{
"loader": {
    "type": "csv",
    "input_path": "/mnt/chembl_new.csv",
    "input_column_names": ["smiles"],
    "target_column_names": ["25","43","47","50","51","52","56","61","72","86","87","88","93","96","100","102","106","107","121","125","126","127","129","134","136","137","144","155","165","169","170","219","227","249","252","259","10140","10472","10670","11359","104301","104302","104756","104828"]
},
"splitter": {
    "type": "descriptor",
    "descriptor": "MolWt",
    "splits": {"train": 0.8, "test": 0.2},
    "seed": 42,
    "bins_count": 10
},
"checkpoint_path": "/mnt/checkpoint.182",
...
}
```

When I run `kmol predict`, I obtain an output file with zeros and ones as expected.

My question is how I can predict values when I have only ID and SMILES information. For example, let's suppose I have a CSV file with only the following information, and I want the predicted values of the columns specified above. 
```
id,smiles
1,[SH0](=O)(C)c1ccc(-c2[nH]c(c(-c3ccc(F)cc3)n2)-c2ccncc2)cc1
2,Clc1ccc(C(N2CCN(CCOCC(=O)O)CC2)c2ccccc2)cc1
3,O=C(OC)C(Cc1cc2OCOc2cc1)c1c2c(nc3c1cccc3)cccc2
```

I tried to set `"splitters"."splits": {"train": 0, "test": 1},`, resulting in 
`ValueError: train_size=0.0 should be either positive and smaller than the number of samples 3 or a float in the (0, 1) range`

I also tried the following CSV without modifying the `splits`, resulting in `ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.`
```
id,smiles,25,43,47,50,51,52,56,61,72,86,87,88,93,96,100,102,106,107,121,125,126,127,129,134,136,137,144,155,165,169,170,219,227,249,252,259,10140,10472,10670,11359,104301,104302,104756,104828
1,[SH0](=O)(C)c1ccc(-c2[nH]c(c(-c3ccc(F)cc3)n2)-c2ccncc2)cc1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,Clc1ccc(C(N2CCN(CCOCC(=O)O)CC2)c2ccccc2)cc1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3,O=C(OC)C(Cc1cc2OCOc2cc1)c1c2c(nc3c1cccc3)cccc2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```

Is what I want to achieve possible at all? And if yes, how should it be done? 

Thank you.

**Comment by romeoc** [comment]
To solve this problem, I recommend 2 changes to the configuration:

1. **Removing unused columns**: since the target columns are not present nor needed here, they can be removed from the list of target columns.
```
"loader": {
    "type": "csv",
    "input_path": "/mnt/chembl_new.csv",
    "input_column_names": ["smiles"],
    "target_column_names": []
}
```

2. **Defining the split**: A 0% split will not work, but splitters are not limited to "train" and "test" only. It is perfectly alright to have a single split containing 100% of the samples:
```
"splitter": {
    "type": "index",
    "splits": {"test": 1.0}
}
```

**Comment by agrodet** [comment]
Thank you, for your answer. I understand quite better, now.
